project:
  type: website

website:
  title: "Eduardo Strike"
  navbar:
    search: false
    title: false
    left:
      - href: landing/
        text: Home
      - href: about/
        text: About
      - href: productions/
        text: Portfolio
      - href: credits/
        text: Past Work
    right:
      - text: "Contact - eduardo@eduardostrike.com"


format:
  html:
    page-layout: full
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



