project:
  type: website

website:
  title: "Eduardo Strike"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: productions/
        text: Productions
      - href: contact.qmd
        text: Contact

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



