project:
  type: website

website:
  title: "Eduardo Strike"
  navbar:
    search: false
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: productions/
        text: Productions
      - href: contact.qmd
        text: Contact


format:
  html:
    page-layout: full
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



